#!/usr/bin/env bash

# Export list filenames.
export AI_REQUEST=./req-`date +"%y%m%d%H%M.json"` ; \

# Export current directory.
export AI_WORKING_DIR=`pwd -P` ; \

# Join all arguments to form the prompt.
prompt="${*}"

# Inform user that the prompt has not been captured.
[ -z "$prompt" ] && echo "E: Prompt not captured" ; \

# Stop execution if the prompt is not captured.
[ -z "$prompt" ] && exit ; \

# prepare to skip printing help.
showHelp=false ; \

# capture help option.
[ "$1" = "-h" -o "$1" = "--help" ] && showHelp=true ; \

# show help.
[ "$showHelp" = "true" ] && \
echo -e "ai: The power of OpenAI language models on your terminal console.


    Usage: ai foo var


Where foo and var will form the message to the OpenAI language model GPT 3.5 Turbo.

The answer will be displayed on the terminal console.



Tip: Use ridirections to write a file like the next example.

\$ai Please give me a list of cool names for an AI > names.txt

A list of cool names will be written to names.txt." ; \

# stop the execution.
[ "$showHelp" = "true" ] && exit ; \

# Prepare the import JSON file.
echo -e "{ \"prompt\" : \"$prompt\" }" > $AI_REQUEST ; \

# Run the node app.
node /opt/ai/app.js
