#!/usr/bin/env bash

# Export docs to read list filename.
export AI_READ=./read-`date +"%y%m%d%H%M.json"`

# Export current directory.
export AI_WORKING_DIR=`pwd -P`

# # verify args
# echo "${@}"

# initialize docs list
list=()

# loop args
for file in ${@}
do
# obtain realpath, add quote marks and commas
[ -f $file ] && list="${list[@]} \"`realpath $file`\"," || \
# warn if not found
echo "E: File $file not found"
done

# trim last comma
list="${list:0:-1}"

# # verify list
# echo ${list[@]}

# Prepare the import JSON file.
echo -e "{ \"list\" : [$list] }" > $AI_READ

# Run the node app.
node app.js
